# Generated by Django 2.0.7 on 2018-07-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180730_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_artist',
            new_name='artist',
        ),
    ]
